Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2022-10, with the labels that each got.

#1644 Render "No versions available" if there are no OS versions available
  src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
  src/components/filters/__snapshots__/useOperatingSystemFilter.test.js.snap
  src/components/filters/useOperatingSystemFilter.js
  src/components/filters/useOperatingSystemFilter.test.js
  src/modules/OsFilterHelpers.js
  src/store/entities.js
Labels: don't merge

#1652 fix(ESSNTL-726): move change of display name to default details reducer
  config/dev.webpack.config.js
  config/prod.webpack.config.js
  src/store/entityDetails.js
  src/store/reducers.js
Labels: bug

#1668 fix(InventoryTable): ESSNTL-3505 - Only use columns already in the store
  src/components/InventoryTable/EntityTable.js
  src/components/InventoryTable/hooks/useColumns.js
  src/store/entities.js
Labels: bug

#1672 chore(deps): Bump @redhat-cloud-services & @patternfly packages
  package-lock.json
  package.json
  src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
  src/components/GeneralInfo/TextInputModal/__snapshots__/TextInputModal.test.js.snap
  src/components/GeneralInfo/dataMapper/__snapshots__/dataMapper.test.js.snap
Labels: dependencies
