Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2023-07, with the labels that each got.

#1918 feat(ESSNTL-4934): Hide host number if users are not allowed
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
Labels: enhancement

#1919 feat: Integrate /groups/%id with RBAC checks
  src/components/InventoryGroupDetail/EmptyStateNoAccess.js
  src/components/InventoryGroupDetail/GroupDetailHeader.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.js
  src/components/InventoryGroupDetail/__tests__/GroupDetailHeader.test.js
  src/constants.js
Labels: enhancement

#1922 feat(ESSNTL-4935): Check permissions in no groups state
  src/components/InventoryGroups/InventoryGroups.cy.js
  src/components/InventoryGroups/NoGroupsEmptyState.js
Labels: enhancement

#1920 feat(ESSNTL-4939): Add/remove hosts from group permissions
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/GroupSystems/GroupSystems.js
  src/constants.js
Labels: enhancement

#1909 feat(THEEDGE-3359): Add federated module to show edge image information
  src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
  src/components/SystemDetails/GeneralInfo.js
Labels: enhancement

#1921 feat(ESSNTL-5041): Add hosts only if has hosts read permissions
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/GroupSystems/GroupSystems.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroupDetail/NoSystemsEmptyState.js
Labels: enhancement

#1926 feat(ESSNTL-5052): Disable create group button if not authorized
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
  src/components/InventoryGroups/SmallComponents/CreateGroupButton.js
  src/constants.js
Labels: enhancement

#1928 feat(ESSNTL-4938): Disable Manage access if not allowed
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
  src/components/InventoryGroupDetail/GroupDetailInfo.js
  src/components/InventoryGroups/NoGroupsEmptyState.js
  src/constants.js
  src/routes/InventoryGroups.js
Labels: enhancement

#1931 Check for hosts:read before showing group hosts
  src/components/InventoryGroupDetail/EmptyStateNoAccess.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.js
  src/components/InventoryGroupDetail/__tests__/InventoryGroupDetail.test.js
  src/routes/InventoryGroups.js
Labels: enhancement

#1933 fix(ESSNTL-4938): Hide systems count if no hosts:read
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
  src/components/InventoryGroups/InventoryGroups.cy.js
  src/constants.js
Labels: bug

#1932 fix(ESSNTL-4937): Display group name even when can't see hosts
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.js
Labels: bug

#1935 fix(ESSNTL-5052): Opt in resource definition check everywhere
  cypress/support/commands.js
  src/App.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
  src/modules/AsyncInventory.js
Labels: bug, don't merge

#1936 fix: Address some of the RBAC and Inventory groups issues
  package-lock.json
  package.json
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/constants.js
  src/routes/InventoryGroups.js
  src/routes/InventoryGroups.test.js
Labels: bug

#1940 fix(ESSNTL-5043): RBAC and InventoryTable actions
  src/Routes.js
  src/Utilities/constants.js
  src/constants.js
  src/routes/InventoryDetail.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
  src/routes/InventoryTable.test.js
Labels: enhancement

#1938 fix(ESSNTL-4937): Don't check RBAC for Total systems column
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.js
  src/constants.js
Labels: bug

#1939 feat: Improve 403 handling at /groups
  src/Utilities/AccessDenied.js
  src/components/InventoryGroupDetail/EmptyStateNoAccess.js
  src/components/InventoryGroups/InventoryGroups.js
  src/components/InventoryTable/__snapshots__/InventoryTable.test.js.snap
Labels: enhancement

#1946 fix(ESSNTL-5064): Fix groups filter by more values
  src/components/InventoryTable/EntityTableToolbar.js
  src/components/filters/useGroupFilter.js
Labels: bug

#1947 Limit the height of groups filter list
  src/components/InventoryTable/EntityTableToolbar.js
  src/components/InventoryTable/EntityTableToolbar.scss
Labels: bug

#1944 fix(ESSNTL-5092): Fix sorting by Total systems (/groups)
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
Labels: bug

#1948 fix(ESSNTL-5110): Improve RBAC checks for delete and edit button on the System details view
  cypress/support/interceptors.js
  src/components/GeneralInfo/BiosCard/__snapshots__/BiosCard.test.js.snap
  src/components/GeneralInfo/CollectionCard/__snapshots__/CollectionCard.test.js.snap
  src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
  src/components/GeneralInfo/DataCollectorsCard/__snapshots__/DataCollectorsCard.test.js.snap
  src/components/GeneralInfo/EditButton/EditButton.js
  src/components/GeneralInfo/EditButton/EditButtonWithAccess.test.js
  src/components/GeneralInfo/EditButton/EditButtonWithNoAccess.test.js
  src/components/GeneralInfo/EditButton/EditButtonWithNoAccessProd.test.js
  src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
  src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
  src/components/GeneralInfo/LoadingCard/LoadingCard.js
  src/components/GeneralInfo/LoadingCard/__snapshots__/LoadingCard.test.js.snap
  src/components/GeneralInfo/OperatingSystemCard/__snapshots__/OperatingSystemCard.test.js.snap
  src/components/GeneralInfo/SystemCard/SystemCard.test.js
  src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
  src/components/GeneralInfo/SystemStatusCard/__snapshots__/SystemStatusCard.test.js.snap
  src/components/GeneralInfo/TextInputModal/TextInputModal.js
  src/components/GeneralInfo/TextInputModal/__snapshots__/TextInputModal.test.js.snap
  src/components/InventoryDetail/TopBar.js
  src/constants.js
  src/routes/InventoryDetail.cy.js
  src/routes/InventoryDetail.js
Labels: bug, enhancement
