Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2023-06, with the labels that each got.

#1878 feat(ESSNTL-3732): Remove hosts from group at /groups/%id
  cypress/support/interceptors.js
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/GroupSystems/GroupSystems.js
  src/components/InventoryGroups/Modals/RemoveHostsFromGroupModal.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
Labels: enhancement

#1889 fix: Hide bulk add to/remove from group under FF
  src/routes/InventoryTable.js
Labels: bug

#1881 fix(essntl-4735): fix for the tags modal filter (filter case sensitivity)
  src/Utilities/TagsModal.js
Labels: bug

#1895 feat(ESSNTL-3736): Add more scenarios to the group deletion modal
  cypress/fixtures/groups.json
  cypress/support/interceptors.js
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryGroupDetail/GroupDetailHeader.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroups/Modals/DeleteGroupModal.cy.js
  src/components/InventoryGroups/Modals/DeleteGroupModal.js
  src/components/InventoryGroups/Modals/__tests__/DeleteGroupModal.test.js
  src/components/InventoryGroups/utils/api.js
Labels: enhancement

#1893 feat(groups): groups filter edit and update for hook
  cypress/fixtures/hosts.json
  src/api/api.js
  src/components/InventoryTable/EntityTableToolbar.js
  src/components/InventoryTable/EntityTableToolbar.test.js
  src/components/filters/__snapshots__/useGroupFilter.test.js.snap
  src/components/filters/useGroupFilter.js
  src/store/action-types.js
  src/store/entities.js
  src/store/inventory-actions.js
Labels: enhancement, Inventory groups

#1906 fix(RHIENG-747): Fix the group delete modal behavior
  cypress/support/interceptors.js
  package-lock.json
  src/components/InventoryGroupDetail/GroupDetailHeader.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroups/Modals/DeleteGroupModal.js
Labels: bug

#1904 fix(ESSNTL-4746): LastSeen filter backend edge case
  src/components/filters/helpers.js
  src/components/filters/useLastSeenFilter.js
Labels: bug

#1912 fix(readme): fixing small error in the run command
  README.md
Labels: bug

#1913 feat(ESSNTL-4934): Require read permissions to access the groups list
  src/components/InventoryGroups/InventoryGroups.cy.js
  src/components/InventoryGroups/InventoryGroups.js
  src/routes/InventoryGroups.js
  src/routes/InventoryGroups.test.js
Labels: enhancement

#1916 fix(RHINENG-736): Vulnerability and Patch tab in Inventory don't show data for RHSM stystems
  src/Utilities/constants.js
  src/Utilities/sharedFunctions.js
  src/Utilities/sharedFunctions.test.js
  src/components/InventoryDetail/ApplicationDetails.js
  src/components/InventoryDetail/DetailHeader.js
  src/components/InventoryDetail/FactsInfo.js
  src/store/entities.js
Labels: bug
