Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2023-11, with the labels that each got.

#2075 chore(ImmutableDevices): cover with cypress tests
  src/components/ImmutableDevices/ImmutableDevices.cy.js
  src/components/ImmutableDevices/ImmutableDevices.js
Labels: tests

#2078 fix(RHIF-72): Fix InventoryTable font size and actions button padding
  src/components/InventoryTable/InventoryList.scss
Labels: bug

#2082 fix(Staleness): Update staleness page to match new backend specs
  src/Utilities/constants.js
  src/components/InventoryHostStaleness/HostStalenessCard.js
  src/components/InventoryHostStaleness/HostStalenessNoAccess.js
  src/components/InventoryHostStaleness/constants.js
  src/components/InventoryTable/__snapshots__/EntityTableToolbar.test.js.snap
Labels: enhancement

#2088 fix(ImmutableDevices): image name should take to image details page
  config/cypress.webpack.config.js
  config/overrideChrome.js
  cypress/support/interceptors.js
  src/components/ImmutableDevices/ImmutableDevices.cy.js
  src/components/ImmutableDevices/columns.js
Labels: blocker

#2086 feat(inventroyGroup): THEEDGE-3693- implement edge group expostion
  src/Routes.js
  src/Utilities/hooks/useEdgeGroups.js
  src/api/api.js
  src/components/InventoryGroups/EdgeGroups.js
  src/routes/InventoryOrEdgeComponent.js
Labels: enhancement

#2106 fix(RHINENG-1423): Enable sorting by last modified
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
Labels: bug

#2103 feat(InventoryGroupDetails): THEEDGE-3539-Add update action to group details
  src/api/edge/updates.js
  src/components/InventoryGroupDetail/EdgeUpdateDeviceModal.js
  src/components/InventoryGroupDetail/GroupDetailHeader.js
  src/components/InventoryGroupDetail/__tests__/GroupDetailHeader.test.js
Labels: enhancement

#2105 fix(ESSNTL-5418): Trim group name before validate
  src/components/InventoryGroups/Modals/CreateGroupModal.js
  src/components/InventoryGroups/Modals/CreateGroupModal.test.js
Labels: bug

#2087 feat(TitleColumn): RHINENG-3112 - Allow passing in a link via href prop
  src/components/ImmutableDevices/ImmutableDevices.cy.js
  src/components/ImmutableDevices/ImmutableDevices.js
  src/components/InventoryTable/EntityTable.js
  src/components/InventoryTable/EntityTable.test.js
  src/components/InventoryTable/EntityTableToolbar.test.js
  src/components/InventoryTable/InventoryTable.js
  src/components/InventoryTable/TitleColumn.js
  src/components/InventoryTable/TitleColumn.test.js
  src/components/InventoryTable/__snapshots__/EntityTable.test.js.snap
  src/components/InventoryTable/__snapshots__/TitleColumn.test.js.snap
  src/components/InventoryTable/helpers.js
  src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
  src/store/entities.js
Labels: enhancement

#2095 test: Use a different way to update window object in tests
  cypress/support/commands.js
  package-lock.json
  package.json
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/ImmutableDevices/ImmutableDevices.cy.js
  src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroups/InventoryGroups.cy.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/CreateGroupModal.cy.js
  src/components/InventoryGroups/Modals/DeleteGroupModal.cy.js
  src/components/InventoryGroups/Modals/RenameGroupModal.cy.js
  src/components/InventoryTable/InventoryTable.cy.js
  src/components/InventoryTabs/HybridInventoryTabs.cy.js
  src/routes/InventoryDetail.cy.js
  src/routes/InventoryTable.cy.js
Labels: tests

#2102 fix(THEEDGE-3703): On immutable tab we can't see the add system option
  src/api/api.js
  src/api/edge/imagesInfo.js
  src/components/GroupSystems/GroupImmutableSystems.js
  src/components/GroupSystems/GroupSystems.js
  src/components/GroupSystems/index.js
  src/components/ImmutableDevices/ImmutableDevices.js
  src/components/ImmutableDevices/columns.js
  src/components/InventoryGroupDetail/GroupTabDetails.js
Labels: bug, enhancement
