Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2023-05, with the labels that each got.

#1853 fix(ESSNTL-4791): Hide all /groups requests under feature flag
  src/components/InventoryTable/EntityTableToolbar.test.js
  src/components/filters/useGroupFilter.js
  src/components/filters/useGroupFilter.test.js
  src/routes/InventoryTable.js
Labels: bug

#1855 fix(ESSNTL-3730): Fix Add host to group API call
  src/components/InventoryGroups/Modals/AddHostToGroupModal.js
  src/components/InventoryGroups/utils/api.js
  src/routes/InventoryTable.js
Labels: bug, Inventory groups

#1858 fix(ESSNTL-4486): Update API functions names
  src/routes/InventoryTable.test.js
  src/store/actions.js
  src/store/inventory-actions.js
Labels: bug

#1859 test: Implement basic cypress tests suite for InventoryTable
  config/cypress.webpack.config.js
  config/overrideChrome.js
  cypress/fixtures/hosts.json
  cypress/support/commands.js
  cypress/support/component.js
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/InventoryTable/InventoryTable.cy.js
Labels: enhancement

#1863 fix(ESSNTL-3730): Add delay before fetching groups again
  src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
Labels: bug

#1862 fix(ESSNTL-4812): Fix Global filter on refresh
  src/components/InventoryTable/InventoryTable.js
Labels: bug

#1869 fix(essntl-3736): fix for group deletion
  src/components/GroupsTable/GroupsTable.js
Labels: bug

#1870 Add host to group
  src/components/InventoryGroups/Modals/AddHostToGroupModal.cy.js
  src/components/InventoryGroups/Modals/AddHostToGroupModal.js
  src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
  src/components/filters/useGroupFilter.js
Labels: enhancement

#1873 fix: Reload table when changing the host group
  src/components/InventoryTable/InventoryList.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
Labels: enhancement

#1876 fix(Groups): Fix incorrect API keys resolution
  cypress/fixtures/groups.json
  cypress/fixtures/groups/620f9ae75A8F6b83d78F3B55Af1c4b2C.json
  cypress/fixtures/groupsSecondPage.json
  cypress/support/interceptors.js
  src/__mocks__/mockedGroups.json
  src/components/GroupSystems/GroupSystems.js
  src/components/GroupSystems/index.js
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/CreateGroupModal.cy.js
  src/components/InventoryGroups/utils/api.js
Labels: bug

#1875 feat(ESSNTL-4491): Sync URLSearchParams with the table filters
  src/Utilities/URLSearchParams.js
  src/Utilities/URLSearchParams.test.js
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
Labels: enhancement

#1874 feat: Enable bulk hosts addition/removal to/from groups
  cypress/fixtures/groups.json
  cypress/fixtures/hosts.json
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
  src/components/InventoryGroups/Modals/RemoveSelectedHostsFromGroupModal.js
  src/components/InventoryGroups/utils/api.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
Labels: enhancement

#1877 fix: Use the same endpoint to add hosts to group
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
  src/components/InventoryGroups/utils/api.js
  src/routes/InventoryTable.cy.js
Labels: bug
