Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2023-08, with the labels that each got.

#1950 Inventory table: check RBAC on the group level when enabling actions
  src/Utilities/constants.js
  src/components/InventoryTable/ActionWithRBAC.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
  src/routes/InventoryTable.test.js
Labels: enhancement

#1966 fix(ESSNTL-5209): Manage access button and RBAC
  src/components/InventoryGroupDetail/GroupDetailInfo.cy.js
  src/components/InventoryGroupDetail/GroupDetailInfo.js
  src/components/InventoryTable/ActionWithRBAC.js
  src/constants.js
Labels: enhancement, Inventory groups

#1963 fix(ESSNTL-5176): hosts read granular permissions for inventory table
  src/Utilities/Wrapper.js
  src/components/InventoryTable/InventoryTable.cy.js
  src/routes/InventoryTable.cy.js
Labels: bug, Inventory groups

#1967 fix(ESSNTL-5172): Alter permissions for add systems button
  cypress/support/commands.js
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/GroupSystems/GroupSystems.js
  src/components/InventoryGroupDetail/InventoryGroupDetail.cy.js
  src/components/InventoryGroupDetail/NoSystemsEmptyState.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
Labels: bug, Inventory groups

#1977 fix: Use the context version of usePermissions
  package-lock.json
  package.json
  src/Utilities/Wrapper.js
Labels: bug

#1979 fix: Add Inventory groups popover
  src/components/InventoryGroups/SmallComponents/Popover.js
  src/routes/InventoryGroups.js
Labels: enhancement, Inventory groups

#1981 fix(RHINENG-993): Use p tag instead small for list items
  src/components/GeneralInfo/InfoTable/InfoTable.js
  src/components/GeneralInfo/InfoTable/__snapshots__/InfoTable.test.js.snap
Labels: bug

#1980 fix(ESSNTL-5171): Active edit buttons must have blue color
  src/components/GeneralInfo/EditButton/EditButton.js
  src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
  src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
Labels: bug

#1964 fix(RHINENG-767): Fix group table loading
  src/components/GroupSystems/GroupSystems.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
  src/components/InventoryGroups/Modals/Modal.js
  src/components/InventoryGroups/Modals/RemoveHostsFromGroupModal.js
Labels: bug, Inventory groups

#1973 fix(ESSNTL-5239): Improve RBAC check for per-row group actions
  src/components/InventoryTable/ActionWithRBAC.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
Labels: enhancement, Inventory groups

#1974 fix(ESSNTL-5239): Improve RBAC check for bulk group actions
  src/components/InventoryGroups/Modals/RemoveHostsFromGroupModal.js
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
Labels: enhancement, Inventory groups

#1975 fix(ESSNTL-5136): Check RBAC for null group id when a host is not in any group
  package-lock.json
  package.json
  src/components/GeneralInfo/EditButton/EditButton.js
  src/routes/InventoryDetail.cy.js
  src/routes/InventoryDetail.js
Labels: enhancement, Inventory groups

#1978 feat(ESSNTL-5214): Granular RBAC for actions & groups table
  src/components/GroupsTable/GroupsTable.cy.js
  src/components/GroupsTable/GroupsTable.js
Labels: enhancement, Inventory groups

#1976 fix(ESSNTL-5210): Check RBAC for null group id when hosts are not in any group
  src/routes/InventoryTable.cy.js
  src/routes/InventoryTable.js
Labels: enhancement, Inventory groups

#1984 fix(ESSNTL-4924): Fetch all groups when building groups filter
  src/components/GroupSystems/GroupSystems.cy.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.cy.js
  src/components/filters/__snapshots__/useGroupFilter.test.js.snap
  src/components/filters/useGroupFilter.js
  src/components/filters/useGroupFilter.test.js
Labels: bug

#1985 fix(ESSNTL-4667): Disable global filter at groups views
  src/components/InventoryGroupDetail/index.js
  src/routes/InventoryGroups.js
Labels: bug

#1968 chore(ESSNTL-4076): Upgrade react-router-dom to version 6
  config/dev.webpack.config.js
  config/overrideChrome.js
  config/prod.webpack.config.js
  config/setupTests.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/App.js
  src/AppEntry.js
  src/Routes.js
  src/Utilities/RouterWrapper.js
  src/Utilities/TestingUtilities.js
  src/components/GeneralInfo/BiosCard/BiosCard.test.js
  src/components/GeneralInfo/BiosCard/__snapshots__/BiosCard.test.js.snap
  src/components/GeneralInfo/CollectionCard/CollectionCard.test.js
  src/components/GeneralInfo/CollectionCard/__snapshots__/CollectionCard.test.js.snap
  src/components/GeneralInfo/ConfigurationCard/ConfigurationCard.test.js
  src/components/GeneralInfo/ConfigurationCard/__snapshots__/ConfigurationCard.test.js.snap
  src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
  src/components/GeneralInfo/GeneralInformation/GeneralInformation.test.js
  src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
  src/components/GeneralInfo/InfrastructureCard/InfrastructureCard.test.js
  src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
  src/components/GeneralInfo/LoadingCard/LoadingCard.js
  src/components/GeneralInfo/LoadingCard/LoadingCard.test.js
  src/components/GeneralInfo/LoadingCard/__snapshots__/LoadingCard.test.js.snap
  src/components/GeneralInfo/OperatingSystemCard/OperatingSystemCard.test.js
  src/components/GeneralInfo/OperatingSystemCard/__snapshots__/OperatingSystemCard.test.js.snap
  src/components/GeneralInfo/SystemCard/SystemCard.test.js
  src/components/GeneralInfo/SystemCard/__snapshots__/SystemCard.test.js.snap
  src/components/GroupSystems/GroupSystems.js
  src/components/GroupsTable/GroupsTable.js
  src/components/InventoryDetail/SystemNotFound.js
  src/components/InventoryDetail/SystemNotFound.test.js
  src/components/InventoryDetail/TopBar.js
  src/components/InventoryDetail/TopBar.test.js
  src/components/InventoryDetail/__snapshots__/SystemNotFound.test.js.snap
  src/components/InventoryDetail/helpers.js
  src/components/InventoryGroupDetail/GroupDetailHeader.js
  src/components/InventoryTable/EntityTable.js
  src/components/InventoryTable/EntityTable.test.js
  src/components/SystemDetails/Compliance.js
  src/components/SystemDetails/Ros.js
  src/components/SystemDetails/Vulnerability.js
  src/components/VulnerabilityEdgePrompt.js
  src/modules/AsyncInventory.js
  src/modules/InventoryTable.js
  src/routes/InventoryDetail.cy.js
  src/routes/InventoryDetail.js
  src/routes/InventoryTable.js
  src/routes/SystemUpdate.js
Labels: enhancement, dependencies

#1988 fix: Add loading styling for manage access button
  src/components/InventoryGroupDetail/GroupDetailInfo.js
Labels: bug

#1996 fix(RHINENG-1420): Fix options duplicates in group search
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
  src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
Labels: bug

#1993 fix(ESSNTL-5252): Hide Create a new group button if not permitted
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.scss
  src/components/InventoryGroups/Modals/Modal.js
  src/components/InventoryGroups/SmallComponents/CreateGroupButton.js
  src/components/InventoryTable/InventoryTable.cy.js
Labels: bug

#2000 fix(ESSNTL-5253): Check tab permissions
  src/ApplicationTab.js
  src/constants.js
  src/routes/InventoryDetail.js
Labels: bug

#1999 fix(ESSNTL-5252): In Add system modal, load writable groups
  config/overrideChrome.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.cy.js
  src/components/InventoryGroups/Modals/AddSelectedHostsToGroupModal.js
  src/components/InventoryGroups/Modals/ModalSchemas/schemes.js
  src/components/InventoryGroups/utils/api.js
  src/constants.js
Labels: bug

#2001 fix: Do not add history entry on host details page
  src/routes/InventoryDetail.js
Labels: bug

#2002 fix(ESSNTL-5253): Fix the broken inventory details tabs
  src/ApplicationTab.js
  src/routes/InventoryDetail.js
Labels: bug

#2003 fix(ESSNTL-5253): Change required permissions for tabs
  package-lock.json
  package.json
  src/App.js
  src/ApplicationTab.js
  src/constants.js
Labels: bug

#2010 feat(ESSNTL-4494): Implement searchable group filter
  src/components/InventoryTable/InventoryTable.cy.js
  src/components/filters/SearchableGroupFilter.js
  src/components/filters/__snapshots__/useGroupFilter.test.js.snap
  src/components/filters/useGroupFilter.js
  src/components/filters/useGroupFilter.test.js
Labels: enhancement
