Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2024-01, with the labels that each got.

#2126 test: Add tests for remove hosts from group modal
  src/components/InventoryGroups/Modals/RemoveHostsFromGroupModal.js
  src/components/InventoryGroups/Modals/__tests__/RemoveHostsFromGroupModal.test.js
Labels: tests

#2128 refactor(InventoryTable): Deprecate unused actions
  src/store/action-types.js
  src/store/entities.js
  src/store/inventory-actions.js
Labels: refactor

#2131 fix(RHINENG-5953): Fix zero state not loading on no systems
  src/Routes.js
  src/Routes.test.js
Labels: bug

#2133 Chore: Update README With 'Common Problems Users Might Encounter' Section
  README.md
Labels: question

#2130 Feat(RHINENG-4796): Add Public IP & FQDN to Infrastructure Card in Host Details Page
  src/api/api.js
  src/components/GeneralInfo/GeneralInformation/__snapshots__/GeneralInformation.test.js.snap
  src/components/GeneralInfo/InfrastructureCard/InfrastructureCard.js
  src/components/GeneralInfo/InfrastructureCard/__snapshots__/InfrastructureCard.test.js.snap
  src/components/GeneralInfo/selectors/selectors.js
Labels: enhancement

#2132 Render host or id if display_name not available in TagsModal
  src/Utilities/TagsModal.js
Labels: bug

#2138 fix(RHINENG-7083): Temporarily ignore 403 when checking hosts count
  src/Routes.js
Labels: bug
