Repository RedHatInsights/insights-inventory-frontend, pull requests merged in 2025-05, with the labels that each got.

#2419 feat(RHINENG-17382): Convert class component GeneralInformation into functional one
  src/components/GeneralInfo/GeneralInformation/GeneralInformation.js
  src/components/GeneralInfo/InfoTable/InfoTable.js
Labels: refactor

#2446 fix(RHINENG-14652): Fix column titles, rename Ansible workload
  src/components/GeneralInfo/SystemCard/SystemCard.test.js
  src/components/GeneralInfo/SystemCard/SystemCardConfigs.js
  src/components/GeneralInfo/SystemCard/SystemCardTestsFixtures.js
  src/components/GeneralInfo/dataMapper/dataMapper.js
  src/components/GeneralInfo/dataMapper/dataMapper.test.js
Labels: bug

#2457 refactor(RHINENG-17799): update ungrouped hosts
  cypress/support/interceptors.js
  src/components/InventoryDetail/DetailRenderer.js
  src/components/InventoryGroups/Modals/AddSystemsToGroupModal.js
  src/components/InventoryTable/EntityTableToolbar.js
  src/components/InventoryTable/InventoryTable.cy.js
  src/components/InventoryTable/InventoryTable.js
  src/components/InventoryTabs/ConventionalSystems/ConventionalSystemsTab.js
  src/components/InventoryTabs/ConventionalSystems/useTableActions.js
  src/components/filters/SearchableGroupFilter.js
  src/components/filters/SearchableGroupFilter.test.js
  src/components/filters/useGroupFilter.js
  src/components/filters/useGroupFilter.test.js
  src/routes/InventoryComponents/HybridInventory.cy.js
Labels: help wanted
